export const DEPARTMENTS = [
    'Aerospace Engineering',
    'Agricultural Engineering',
    'Artificial Intelligence and Data Science',
    'Artificial Intelligence and Machine Learning',
    'Automobile Engineering',
    'Biomedical Engineering',
    'Biotechnology',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science and Business Systems',
    'Computer Science and Design',
    'Computer Science and Engineering',
    'Computer Technology',
    'Electrical and Electronics Engineering',
    'Electronics and Communication Engineering',
    'Electronics and Instrumentation Engineering',
    'Fashion Technology',
    'Food Technology',
    'Information Science and Engineering',
    'Information Technology',
    'Instrumentation and Control Engineering',
    'Mechanical Engineering',
    'Mechatronics Engineering',
    'Medical Electronics',
    'Petrochemical Engineering',
    'Petroleum Engineering',
    'Pharmaceutical Technology',
    'Robotics and Automation',
    'Textile Technology',
    'Master of Business Administration'
];
